
FROM node:18-alpine

WORKDIR /cheko-frontend


COPY package.json package-lock.json* ./


RUN npm install

COPY . .


EXPOSE 3000


ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

CMD ["npm", "run", "dev"]