version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_CHEKO
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - "5436:5432"
    volumes:
      - ./seeds:/seeds
    working_dir: /seeds
    networks:
      - spring-net

  cheko-api:
    build: ./CHEKO
    container_name: cheko-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3001:3001"
    networks:
      - spring-net

volumes:
  pgdata:

networks:
  spring-net:
