apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: cheko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name:  db-cheko
        image: ddd
        resources:
        ports:
        - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypass
        volumeMounts:
            - name: postgres-seed
              mountPath: /seeds
      volumes:
        - name: postgres-seed
          hostPath:
            path: ./seeds