apiVersion: v1
kind: Service
metadata:
  name: cheko-frontend
  namespace: cheko
spec:
  selector:
    app: cheko-frontend
  ports:
    - port: 3000
      targetPort: 3000
      NodePort: 30080
      
  type: NodePort