import type { Metadata } from "next";
import "./globals.css";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ThemeProviderWrapper from "./config/MuiThemeProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <AppRouterCacheProvider>


        <ThemeProviderWrapper >
      <body className="bg-bg">

          {children}
      </body>
        </ThemeProviderWrapper>

        </AppRouterCacheProvider>
    </html>
  );
}
